# Generated by Django 2.2.2 on 2019-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('main', '0003_remove_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_a_laptop', models.ManyToManyField(blank=True, null=True, to='blog.Product_a_laptop')),
                ('product_phone', models.ManyToManyField(blank=True, null=True, to='blog.Product_Phone')),
                ('product_tv', models.ManyToManyField(blank=True, null=True, to='blog.Product_TV')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_product', to='main.Item'),
        ),
    ]
