# Generated by Django 2.2.2 on 2019-06-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190623_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated',
        ),
    ]
