# Generated by Django 2.2.2 on 2019-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('main', '0007_auto_20190623_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_a_laptop',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Product_a_laptop'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_phone',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Product_Phone'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_tv',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Product_TV'),
        ),
    ]
