# Generated by Django 2.2.2 on 2019-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190623_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_a_laptop',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_phone',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_tv',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_product', to='blog.Product_a_laptop'),
        ),
    ]
