# Generated by Django 2.2.2 on 2019-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('main', '0009_auto_20190623_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product_a_laptop',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_phone',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_product', to='blog.Product_Phone'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_tv',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_product', to='blog.Product_TV'),
        ),
    ]
